// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuvmuorvazhmjnzjfowo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1dm11b3J2YXpobWpuempmb3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjIxNzIsImV4cCI6MjA2ODkzODE3Mn0.rfNdGNUIgeMMw28_ONJi_jH_3B7vlYqsAbe1BXH4Qps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});